catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, CategoryListView, HomePageView, ContactView, \
    CategoryDetailView, BlogDetailView, BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, \
    toggle_published, ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('catalog/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create_product/', ProductCreateView.as_view(), name='product_create'),
    path('update_product/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='cat_prod'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('blog/<slug>', BlogDetailView.as_view(), name='blog'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<slug>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<slug>', BlogDeleteView.as_view(), name='blog_delete'),
    path('published/<int:pk>', toggle_published, name='toggle_published')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, UserRegisterView, confirm_email, recover_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', LogoutView.as_view(), name='profile'),
    path('confirm-register/<str:token>/', confirm_email, name='confirm_email'),
    path('recover_password/', recover_password, name='recover_password'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(upload_to='preview/', **NULLABLE, verbose_name='Фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за штуку')
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                verbose_name='Создатель', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name} {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('set_published', 'Can publish posts'),
            ('change_description', 'Can change description'),
            ('change_category', 'Can change category')
        ]


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='preview/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.PositiveIntegerField(verbose_name='Просмотры', default=0)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(verbose_name='Номер версии')
    version_title = models.CharField(max_length=100, verbose_name='Название версии')
    is_actual_version = models.BooleanField(verbose_name='Признак актуальной версии', default=False)

    def __str__(self):
        return f'{self.version_title}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Blog, Product, Version
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'preview')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        if not User.objects.filter(is_superuser=True):
            exclude = ('creator', 'is_published')
        else:
            fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        wrong = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                 'бесплатно', 'обман', 'полиция', 'радар']
        for word in wrong:
            if word in cleaned_data:
                raise forms.ValidationError('Название содержит недопустимое слово')
        return cleaned_data


class ModeratorForm(ProductForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from pytils.translit import slugify
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from catalog.forms import BlogForm, ProductForm, VersionForm, ModeratorForm
from catalog.models import Product, Category, Blog, Version
from catalog.services import cache_category, cache_product_staff, cache_product


class HomePageView(TemplateView):
    template_name = "catalog/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Домашняя'
        return context


class ContactView(View):
    template_name = 'catalog/contact.html'

    def get(self, request):
        context = {'title': 'Контакты'}
        return render(request, self.template_name, context)

    def post(self, request):
        context = {'title': 'Отправлено!'}
        email = request.POST.get('email')
        message = request.POST.get('message')
        send_mail(f'Обратная связь от {email}', message, settings.EMAIL_HOST_USER, ['skam3840@gmail.com'])
        return render(request, self.template_name, context)


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог'
        context['version_list'] = Version.objects.filter(is_actual_version=True)
        return context

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            return cache_product_staff
        return cache_product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать продукт'
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.user.groups.filter(name='модератор').exists():
            return context_data
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        if self.request.user.groups.filter(name='модератор').exists():
            if form.is_valid():
                self.object = form.save()
                return super().form_valid(form)
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user.groups.filter(name='модератор').exists():
            return ModeratorForm
        if user == self.object.creator or user.is_staff:
            return self.form_class
        raise HttpResponseForbidden


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return cache_category()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        return context


class ProductDetailView(DetailView):
    model = Product


class CategoryDetailView(ListView):
    model = Category
    template_name = 'catalog/product_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        category = Category.objects.get(pk=pk)
        context['title'] = f'{category.name}'
        context['object_list'] = Product.objects.filter(category=pk)
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Блог'
        return context

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_published=True)


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('catalog:blog_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать блог'
        return context

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('catalog:blog', args=[self.kwargs.get('slug')])

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')


def toggle_published(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if blog.is_published:
        blog.is_published = False
    else:
        blog.is_published = True
    blog.save()
    return redirect(reverse('catalog:blog_list'))

catalog/templates/catalog/base.html
{% load static %}
{% load tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title | title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    {% include 'catalog/includes/inc_main_menu.html' %}
</nav>

<main>
    <div class="p-5 mb-5 bg-dark-subtle text-emphasis-dark">
        <div class="container-lg">
            <div class="row text-center">
                <h1 class="mb-5">{{ title | title }}</h1>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'catalog:home' %}" class="nav-link px-2 text-body-secondary">Дом</a>
            </li>
            <li class="nav-item"><a href="{% url 'catalog:contact' %}" class="nav-link px-2 text-body-secondary">Контакты</a>
            </li>
            <li class="nav-item"><a href="{% url 'catalog:catalog' %}"
                                    class="nav-link px-2 text-body-secondary">Каталог</a></li>
            <li class="nav-item"><a href="{% url 'catalog:categories' %}"
                                    class="nav-link px-2 text-body-secondary">Категории</a></li>
            <li class="nav-item"><a href="\admin" class="nav-link px-2 text-body-secondary">Админ</a></li>
        </ul>
        <p class="text-center text-body-secondary">© {% now 'Y'%}</p>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="card col-6">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Хотите удалить {{object.title}} ?</p>
                <button type="submit" class="btn btn-success">Подтвердить</button>
                <a type="button" class="btn btn-danger" href="{% url 'catalog:blog_list' %}">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title  text-center">{{ object.title }}</h1>
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <img src="{% media object.preview %}" class="card-img-top">
                </div>
            </div>
            <p class="card-text">{{object.content}}</p>
            <p class="card-text"><small class="text-muted">{{object.created_at}}</small></p>
            <p class="card-text"><small class="text-muted">Количество просмотров {{object.views_count}}</small></p>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="card col-6">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="row container">
    <div class="col-4"></div>
    <div class="col-4">
        <a type="button" class="btn btn-success mb-5 rounded-3 col-12"
           href="{% url 'catalog:blog_create' %}">Создать</a>
    </div>
    <div class="col-4"></div>
    {% for object in object_list %}
    <div class="col-4 mb-4">
        <div class="card mb-4 rounded-3">
            <div class="card-header py-3  text-center">
                <h4 class="my-0 fw-normal">{{object.title}}</h4>
            </div>
            <div class="card-body">
                <img src="{% media object.preview %}" class="card-img-top mb-2">
                <p>
                    {{object.content|string_slice}}
                </p>
                <div class="card-footer">
                    <p class="card-text"><small class="text-muted">{{object.created_at}}</small></p>
                    <p class="card-text"><small class="text-muted">Количество просмотров {{object.views_count}}</small>
                    </p>
                    <p class="card-text"><a class="text-muted" href="{% url 'catalog:toggle_published' object.pk %}">
                        Деактивировать</a>
                    </p>
                    <div class="row">
                        <div class="btn-group" role="group">
                            <a type="button" class="btn btn-outline-success col-4"
                               href="{% url 'catalog:blog' object.slug %}">Подробнее</a>
                            <a type="button" class="btn btn-secondary col-4"
                               href="{% url 'catalog:blog_update' object.slug %}">Изменить</a>
                            <a type="button" class="btn btn-danger col-4"
                               href="{% url 'catalog:blog_delete' object.slug %}">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    <div class="row container text-center">
        {% for object in object_list %}
            <div class="col-4">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.name | title }}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{object.description | title}}
                    </p>
                    <a type="button" class="btn btn-success" href="{% url 'catalog:cat_prod' object.pk %}">Список</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <img src="{{ 'contact.jpg'|my_media  }}"
                 class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">Шипилов Максим</h5>
                <p class="card-text">г. Самара, тел. 8 (960) 830-74-51</p>
            </div>
        </div>
    </div>

    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="Email" class="form-label">Адрес электронной почты</label>
                <input name="email" type="email" class="form-control" id="Email" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">Мы никогда никому не передадим вашу электронную почту.</div>
            </div>
            <div class="mb-3">
                <label for="Text" class="form-label">Ваш вопрос</label>
                <textarea name="message" class="form-control" id="Text" rows="5"></textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="Написать">
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-center">
<p>Будь как дома путник, я ни в чём не откажу</p>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body text-center">
                <h5 class="card-title">{{ object.name | title}}</h5>
                <img src="{% media object.preview %}" class="card-img-top">
                <p class="card-text">{{object.description | title}}</p>
                <p class="card-text"><small class="text-muted">{{object.updated_at}}</small></p>
                <a type="button" class="btn btn-success text-center" href="#">В корзину</a>
                {% if perms.catalog.change_description or user == object.creator %}
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
                {% endif %}
            </div>
            <div class="card-footer">
                <span class="text-muted">{{object.creator|default:'SkyPro'}}</span>
                {% for version in version_list %}
                    {% if version.product_id == object.id %}
                        {{ version.version_title }}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load tags %}
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        {% if perms.catalog.change_version %}
        {% if formset.management_form %}
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="row container text-center">
    {% if user.is_authenticated %}
    <div class="col-4"></div>
    <div class="col-4">
        <a type="button" class="btn btn-success mb-5 rounded-3 col-12"
           href="{% url 'catalog:product_create' %}">Создать</a>
    </div>
    <div class="col-4"></div>
    {% endif %}
    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{object.name | title}}</h4>
            </div>
            <div class="card-body">
                <img src="{% media object.preview %}" class="card-img-top">
                <p>
                    {{object.description | title}}
                </p>
                <h2 class="card-title pricing-card-title">{{object.price}} руб.</h2>
                <a type="button" class="btn btn-success" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
                {% if perms.catalog.change_description or user == object.creator %}
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
                {% endif %}
            </div>
            <div class="card-footer">
                <span class="text-muted">{{object.creator|default:'SkyPro'}}</span>
                {% for version in version_list %}
                    {% if version.product_id == object.id %}
                        {{ version.version_title }}
                    {% endif %}
                {% endfor %}
                <br>
                {% if object.is_published %}
                    Активно
                {% else %}
                    Бан
                {% endif %}

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}